name: Setup upstream libseccomp
description: "Install gperf and libseccomp"
runs:
  using: "composite"
  steps:
  - run: sudo apt-get install gperf
    shell: bash
  - run: |
      LIBSECCOMP_VERSION="2.5.1"
      curl -sSLO "https://github.com/seccomp/libseccomp/releases/download/v${LIBSECCOMP_VERSION}\
      /libseccomp-${LIBSECCOMP_VERSION}.tar.gz"
      tar xvf "libseccomp-${LIBSECCOMP_VERSION}.tar.gz"
      pushd "libseccomp-${LIBSECCOMP_VERSION}"
      ./configure
      make
      sudo make install
    shell: bash
