[package]
name = "libseccomp-sys"
version = "0.1.1"
authors = ["Manabu Sugimoto <Manabu.Sugimoto@sony.com>"]
license = "MIT OR Apache-2.0"
description = "Raw FFI bindings for libseccomp library"
homepage = "https://github.com/ManaSugi/libseccomp-rs"
repository = "https://github.com/ManaSugi/libseccomp-rs"
categories = ["seccomp", "api-bindings"]
edition = "2018"
readme = "README.md"
