name: build-test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, edited, synchronize]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install upstream libseccomp
        run: sudo ./scripts/install_libseccomp.sh
      - name: Build crate
        run: make debug

  fmt:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare for rustfmt
        run: rustup component add rustfmt
      - name: Run rustfmt
        run: make fmt

  clippy:
    name: Clippy Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install upstream libseccomp
        run: sudo ./scripts/install_libseccomp.sh
      - name: Prepare for clippy
        run: rustup component add clippy
      - name: run clippy
        run: make clippy

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install upstream libseccomp
        run: sudo ./scripts/install_libseccomp.sh
      - name: Run test
        run: make test

  static-link-gnu:
    name: Static-link Check for GNU libc
    runs-on: ubuntu-latest
    env:
      LIBSECCOMP_LINK_TYPE: static
      LIBSECCOMP_LIB_PATH: /usr/local/lib
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install upstream libseccomp
        run: sudo ./scripts/install_libseccomp.sh
      - name: Build crate
        run: make build
      - name: Run test
        run: make test

  static-link-musl:
    name: Static-link Check for musl libc
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
    env:
      LIBSECCOMP_LINK_TYPE: static
      LIBSECCOMP_LIB_PATH: /usr/local/libseccomp-musl/lib
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        run: rustup target add ${{ matrix.target }}
      - name: Install musl gcc
        run: sudo apt-get install musl-tools
      - name: Install upstream libseccomp
        run: |
          install_dir=$(dirname ${{ env.LIBSECCOMP_LIB_PATH }})
          sudo ./scripts/install_libseccomp.sh -m -i ${install_dir}
      - name: Build crate
        run: cargo build --target ${{ matrix.target }}
      - name: Run test
        run: cargo test --target ${{ matrix.target }} -- --nocapture --test-threads 1

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - all-features
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install upstream libseccomp
        run: sudo ./scripts/install_libseccomp.sh
      - name: Run cargo tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: '--${{ matrix.features }}'
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
